Modify snapshot model to match MongoDB
UBC-VCL/VCL-content-platform-server pull request #17
Opened 2023-06-14 04:08 UTC by svolterra

## Description

A PR to fix the following mismatch between fields in the back-end server and those found in MongoDB for the Snapshot model.

<img alt="mongodb snapshot model" width="400" src="https://github.com/UBC-VCL/VCL-content-platform-server/assets/71746168/1bb96ad8-4b70-4da3-b0e7-2950984d618c">

<img alt="mongodb snapshot model" width="400" src="https://github.com/UBC-VCL/VCL-content-platform-server/assets/71746168/f64aa598-39cb-4af2-8e01-ae612699aa5d">

### Changes

* [Please list the main changes made in point form]

### Updates

[Please enter a brief summary of updates to this PR during code review - if any]

## Checklist

- [ ] Ran `npm run lint:fix` to format code
- [ ] Assigned PR to all authors
- [ ] Requested at least one reviewer

2023-06-15 04:22 UTC, WYC401 commented on models/snapshot.model.js
> +    hyperlinks: [{ type: String }],
the hyperlinks does not appear in timelinecontroller

2023-06-15 04:22 UTC, WYC401 requested changes
also the

2023-06-15 04:57 UTC, svolterra commented on models/snapshot.model.js
> +    hyperlinks: [{ type: String }],
Great catch! 🙌

2023-06-16 00:05 UTC, WYC401 approved these changes
LGTM

2023-06-16 01:23 UTC, ElisaHu1 approved these changes

2023-06-16 07:33 UTC, merged